# Generated by Django 3.0.5 on 2020-04-29 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 15, 48, 50, 803824, tzinfo=utc)),
        ),
    ]
