# Generated by Django 3.0.5 on 2020-04-29 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200429_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2020, 4, 29, 18, 12, 58, 483102, tzinfo=utc)),
        ),
    ]
