# Generated by Django 3.0.5 on 2020-04-29 22:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200429_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 29, 22, 15, 42, 64755, tzinfo=utc)),
        ),
    ]
