# Generated by Django 3.0.5 on 2020-04-30 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200430_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 0, 25, 23, 470292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
